[2025-04-11T02:59:20.235+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-11T02:59:20.254+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.data_loading scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-11T02:59:20.265+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.data_loading scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-11T02:59:20.266+0000] {taskinstance.py:2856} INFO - Starting attempt 7 of 8
[2025-04-11T02:59:20.279+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): data_loading> on 2025-04-10 00:00:00+00:00
[2025-04-11T02:59:20.288+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1325) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-11T02:59:20.290+0000] {standard_task_runner.py:72} INFO - Started process 1330 to run task
[2025-04-11T02:59:20.290+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'data_loading', 'scheduled__2025-04-10T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dag_for_workshop.py', '--cfg-path', '/tmp/tmppre0uu8x']
[2025-04-11T02:59:20.293+0000] {standard_task_runner.py:105} INFO - Job 42: Subtask data_loading
[2025-04-11T02:59:20.345+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.data_loading scheduled__2025-04-10T00:00:00+00:00 [running]> on host c97e2588350c
[2025-04-11T02:59:20.434+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='example@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='data_loading' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-10T00:00:00+00:00'
[2025-04-11T02:59:20.435+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-11T02:59:20.438+0000] {etl.py:82} ERROR - Error loading data to database: the JSON object must be str, bytes or bytearray, not NoneType
[2025-04-11T02:59:20.438+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-11T02:59:20.447+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-11T02:59:20.448+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=data_loading, run_id=scheduled__2025-04-10T00:00:00+00:00, execution_date=20250410T000000, start_date=20250411T025920, end_date=20250411T025920
[2025-04-11T02:59:20.466+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-04-11T02:59:20.479+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-11T02:59:20.481+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
