[2025-04-11T01:24:37.778+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-11T01:24:37.799+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.data_loading scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-11T01:24:37.811+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.data_loading scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-11T01:24:37.812+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2025-04-11T01:24:37.824+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): data_loading> on 2025-04-10 00:00:00+00:00
[2025-04-11T01:24:37.833+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=112) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-11T01:24:37.835+0000] {standard_task_runner.py:72} INFO - Started process 118 to run task
[2025-04-11T01:24:37.834+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'data_loading', 'scheduled__2025-04-10T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag_for_workshop.py', '--cfg-path', '/tmp/tmpj3hhwo0e']
[2025-04-11T01:24:37.837+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask data_loading
[2025-04-11T01:24:37.885+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.data_loading scheduled__2025-04-10T00:00:00+00:00 [running]> on host ebadb61ea72f
[2025-04-11T01:24:37.967+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='example@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='data_loading' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-10T00:00:00+00:00'
[2025-04-11T01:24:37.969+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-11T01:24:37.971+0000] {etl.py:82} ERROR - Error loading data to database: the JSON object must be str, bytes or bytearray, not NoneType
[2025-04-11T01:24:37.972+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-11T01:24:37.990+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-11T01:24:37.991+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=data_loading, run_id=scheduled__2025-04-10T00:00:00+00:00, execution_date=20250410T000000, start_date=20250411T012437, end_date=20250411T012437
[2025-04-11T01:24:38.052+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-04-11T01:24:38.075+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-11T01:24:38.091+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
