[2025-04-11T01:24:33.994+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-11T01:24:34.008+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.data_merging scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-11T01:24:34.016+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.data_merging scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-11T01:24:34.017+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2025-04-11T01:24:34.030+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): data_merging> on 2025-04-10 00:00:00+00:00
[2025-04-11T01:24:34.038+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=108) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-11T01:24:34.039+0000] {standard_task_runner.py:72} INFO - Started process 110 to run task
[2025-04-11T01:24:34.041+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'data_merging', 'scheduled__2025-04-10T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag_for_workshop.py', '--cfg-path', '/tmp/tmphhtbuj8c']
[2025-04-11T01:24:34.044+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask data_merging
[2025-04-11T01:24:34.100+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.data_merging scheduled__2025-04-10T00:00:00+00:00 [running]> on host ebadb61ea72f
[2025-04-11T01:24:35.177+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='example@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='data_merging' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-10T00:00:00+00:00'
[2025-04-11T01:24:35.179+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-11T01:24:35.911+0000] {etl.py:75} ERROR - Error merging data: the JSON object must be str, bytes or bytearray, not NoneType
[2025-04-11T01:24:35.948+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-11T01:24:35.959+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-11T01:24:35.960+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=data_merging, run_id=scheduled__2025-04-10T00:00:00+00:00, execution_date=20250410T000000, start_date=20250411T012434, end_date=20250411T012435
[2025-04-11T01:24:35.986+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-04-11T01:24:36.007+0000] {taskinstance.py:3891} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-04-11T01:24:36.010+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
