[2025-04-11T01:29:27.767+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-11T01:29:27.782+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.data_merging scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-11T01:29:27.790+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.data_merging scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-11T01:29:27.792+0000] {taskinstance.py:2856} INFO - Starting attempt 5 of 6
[2025-04-11T01:29:27.802+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): data_merging> on 2025-04-10 00:00:00+00:00
[2025-04-11T01:29:27.810+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=138) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-11T01:29:27.812+0000] {standard_task_runner.py:72} INFO - Started process 140 to run task
[2025-04-11T01:29:27.811+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'data_merging', 'scheduled__2025-04-10T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/dag_for_workshop.py', '--cfg-path', '/tmp/tmp9r17lwob']
[2025-04-11T01:29:27.813+0000] {standard_task_runner.py:105} INFO - Job 31: Subtask data_merging
[2025-04-11T01:29:27.850+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.data_merging scheduled__2025-04-10T00:00:00+00:00 [running]> on host c97e2588350c
[2025-04-11T01:29:28.669+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='example@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='data_merging' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-10T00:00:00+00:00'
[2025-04-11T01:29:28.670+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-11T01:29:29.327+0000] {etl.py:75} ERROR - Error merging data: the JSON object must be str, bytes or bytearray, not NoneType
[2025-04-11T01:29:29.349+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-11T01:29:29.357+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-11T01:29:29.358+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=data_merging, run_id=scheduled__2025-04-10T00:00:00+00:00, execution_date=20250410T000000, start_date=20250411T012927, end_date=20250411T012929
[2025-04-11T01:29:29.394+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-04-11T01:29:29.413+0000] {taskinstance.py:3891} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-04-11T01:29:29.417+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
